# Generated by Django 5.0.4 on 2024-04-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Centre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('cognom', models.CharField(max_length=100)),
                ('edat', models.IntegerField()),
                ('rol', models.CharField(choices=[('estudiant', 'Estudiante'), ('professor', 'Profesor')], max_length=50)),
            ],
        ),
    ]
